### PR TITLE
chore: bump packages

### PR DESCRIPTION
**Pull request by Abhikumar98**
Bumping packages to include recent changes in widget.

JIRA ticket: [Show an indicator that custom settings are applied (LF-1639)](https://lifi.atlassian.net/browse/LF-1639)

### CODE REVIEW

**Review by 0xsebn — APPROVED** [review]

**Review by chybisov — COMMENTED** [review]
Why do we need this update? Please wait until the new widget version with some fixes 🙂

**Comment by Abhikumar98** [comment]
> Why do we need this update? Please wait until the new widget version with some fixes 🙂

There are couple of tickets having dependencies on the new changes. We can wait if there's a deployment happening soon.

**Comment by chybisov** [comment]
@Abhikumar98 please always mention them in the description 🙂

**Review by chybisov — APPROVED** [review]
Now we can merge 🙂

**Pull request merged**
