### PR TITLE
feat: add session id

### PR DESCRIPTION
**Pull request by dennyscode**
Ticket: https://lifi.atlassian.net/browse/LF-8666

### CODE REVIEW

**Review by oktapodia — CHANGES_REQUESTED** [review]
Seems to be overall a lot of duplication. can you do this useEffect/existence check into the hook itself to avoid those duplications?

**Review by tcheee — APPROVED** [review]
lgtm

**Comment by tcheee** [comment]
> Seems to be overall a lot of duplication. can you do this useEffect/existence check into the hook itself to avoid those duplications?

It is mainly for testing purpose for QA team and will be remove when we are ready to move to staging

**Review by oktapodia — APPROVED** [review]
LGTM

**Pull request merged**
