### PR TITLE
add japanese messages on i18n section

### PR DESCRIPTION
**Pull request by hibikikudo**
## Summary

Added Japanese i18n translations. The changes include:

- Added Japanese translations for properties in the `navbar`

### CODE REVIEW

**Comment by chybisov** [comment]
@hibikikudo Hey, thank you for taking the time to help translate Jumper. 

We use the Crowdin platform to manage translations https://crowdin.com/project/jumper-exchange

Please register on Crowdin and translate the Japanese language. After the translation, we will sync it with the repository. Thank you!

**Comment by hibikikudo** [comment]
Thank you for the guidance. I will consider using Crowdin and try to provide Japanese translations.

**Comment by hibikikudo** [comment]
@chybisov 
I complete all translations on Crowdin.
https://crowdin.com/project/jumper-exchange

**Comment by chybisov** [comment]
@hibikikudo hey, thanks for translating the Jumper! 🙂

Could you please consider also translating LI.FI Widget project to Japanese so Jumper could benefit from both translations and can be considered completed https://crowdin.com/project/lifi-widget 

Once that is finished, we could enable it in the Jumper language section. Please also consider joining our [Discord](https://discord.com/channels/849912621360218112/1071021414313902140) and asking for the `@Translator` role. 

Thank you!

**Comment by hibikikudo** [comment]
Hey @chybisov Thank you for the message.
Sure I will try to translate LI.FI Widget. Give me several days:)

**Comment by hibikikudo** [comment]
@chybisov I have completed the translation of the LI.FI Widget into Japanese. 
I would appreciate if someone could verify the work. 
 https://crowdin.com/project/lifi-widget

**Comment by chybisov** [comment]
@hibikikudo thank you! We will take a look soon 🙂

**Pull request closed without merging**
